# Generated by Django 2.2.10 on 2020-11-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('blood_group', models.CharField(choices=[('O+', 'O+'), ('O-', '0-'), ('SS', 'SS')], default='', max_length=100)),
                ('ailment', models.CharField(default='', max_length=100)),
                ('doctor_last_seen', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='images/freelancerAvatar.png', upload_to='images/freeclancers')),
            ],
        ),
    ]
