# Generated by Django 2.2.10 on 2020-11-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20201107_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('middle_name', models.CharField(default='', max_length=100)),
                ('specialization', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('ailment', models.CharField(default='', max_length=100)),
                ('seen_hours', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='images/freelancerAvatar.png', upload_to='images/freeclancers')),
            ],
        ),
    ]
